# Generated by Django 3.0 on 2019-12-16 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalagoComponentes',
            fields=[
                ('NoPart', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='No. De Parte')),
                ('DescriptionComponent', models.TextField(verbose_name='Descripcion del componente')),
                ('Price', models.IntegerField(verbose_name='Costo')),
                ('unity', models.CharField(max_length=50, verbose_name='Unidad')),
                ('TypeService', models.CharField(max_length=50)),
                ('YearPrice', models.DateField(verbose_name='Año')),
                ('Brand', models.CharField(max_length=50, verbose_name='Marca del componente')),
                ('ImageDescription', models.ImageField(blank=True, null=True, upload_to='Componentes/pictures')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCarril',
            fields=[
                ('NoCapufeLane', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='No. Capufe')),
                ('Lane', models.CharField(max_length=3, verbose_name='Carril')),
                ('TypeLane', models.CharField(max_length=15, verbose_name='Tipo De Carril')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPlace',
            fields=[
                ('NoPlazaCapufe', models.IntegerField(primary_key=True, serialize=False, verbose_name='No. Plaza Capufe')),
                ('Place', models.CharField(max_length=30, verbose_name='Plaza')),
                ('Delegacion', models.CharField(max_length=30, verbose_name='Plaza')),
            ],
        ),
        migrations.CreateModel(
            name='DTCEncabezado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NoConvenio', models.IntegerField(unique=True)),
                ('NombreEncargado', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPlaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('noplazacapufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMantenimiento.CatalogoPlace')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_Number', models.CharField(max_length=10, verbose_name='Numero De Telefono: ')),
                ('rol_Usuario', models.CharField(max_length=20, verbose_name='Tipo de usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DTCTecnico',
            fields=[
                ('NoReference', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('NoAXA', models.CharField(max_length=8, unique=True)),
                ('FolioFalla', models.IntegerField(unique=True)),
                ('Estatus', models.CharField(max_length=30)),
                ('DateFalla', models.DateField()),
                ('DateSiniestro', models.DateField()),
                ('DateElaboracion', models.DateField()),
                ('DateEnvio', models.DateField()),
                ('TypeDictamen', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('Diagnostic', models.TextField(blank=True)),
                ('Observation', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('catalagocomponentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMantenimiento.CatalagoComponentes')),
                ('catalogocarril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMantenimiento.CatalogoCarril')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='catalogocarril',
            name='noplazacapufe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMantenimiento.CatalogoPlace'),
        ),
    ]
